version: '3.8'
  
services:
 
  mysql-standalone:
    image: mysql
    container_name: mysql-standalone
    networks:
    - spring-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=dockertest

  accounts:
    image: bimal1993/accounts:latest
    restart: on-failure
    ports:
    - 8080:8081
    networks:
    - spring-net
    depends_on:
      - mysql-standalone
      
  loans:
    image: bimal1993/loans:latest
    restart: on-failure
    ports:
    - 8090:8090
    networks:
    - spring-net
    depends_on:
      - mysql-standalone
    
  cards:
    image: bimal1993/card:latest
    restart: on-failure
    ports:
    - 9000:9000
    networks:
    - spring-net
    depends_on:
      - mysql-standalone
  
networks:
     spring-net:
        